# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"#\n\x0fMensagemRequest\x12\x10\n\x08mensagem\x18\x01 \x01(\t\"!\n\rMensagemReply\x12\x10\n\x08mensagem\x18\x01 \x01(\t2H\n\x04\x43hat\x12@\n\x0e\x45nviarMensagem\x12\x15.chat.MensagemRequest\x1a\x13.chat.MensagemReply(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MENSAGEMREQUEST']._serialized_start=20
  _globals['_MENSAGEMREQUEST']._serialized_end=55
  _globals['_MENSAGEMREPLY']._serialized_start=57
  _globals['_MENSAGEMREPLY']._serialized_end=90
  _globals['_CHAT']._serialized_start=92
  _globals['_CHAT']._serialized_end=164
# @@protoc_insertion_point(module_scope)
