# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cart.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'cart.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncart.proto\x12\rcom.cart.grpc\x1a\x1bgoogle/protobuf/empty.proto\"\x1c\n\tUserQuery\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"J\n\x0f\x43\x61rtItemRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x14\n\x0cproduct_name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"A\n\x08\x43\x61rtItem\x12\x14\n\x0cproduct_name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x02\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"?\n\x04\x43\x61rt\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12&\n\x05items\x18\x02 \x03(\x0b\x32\x17.com.cart.grpc.CartItem2\x95\x02\n\x0b\x43\x61rtService\x12\x43\n\tAddToCart\x12\x1e.com.cart.grpc.CartItemRequest\x1a\x16.google.protobuf.Empty\x12H\n\x0eRemoveFromCart\x12\x1e.com.cart.grpc.CartItemRequest\x1a\x16.google.protobuf.Empty\x12\x38\n\x07GetCart\x12\x18.com.cart.grpc.UserQuery\x1a\x13.com.cart.grpc.Cart\x12=\n\tClearCart\x12\x18.com.cart.grpc.UserQuery\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cart_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERQUERY']._serialized_start=58
  _globals['_USERQUERY']._serialized_end=86
  _globals['_CARTITEMREQUEST']._serialized_start=88
  _globals['_CARTITEMREQUEST']._serialized_end=162
  _globals['_CARTITEM']._serialized_start=164
  _globals['_CARTITEM']._serialized_end=229
  _globals['_CART']._serialized_start=231
  _globals['_CART']._serialized_end=294
  _globals['_CARTSERVICE']._serialized_start=297
  _globals['_CARTSERVICE']._serialized_end=574
# @@protoc_insertion_point(module_scope)
