# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: product.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'product.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x11\x63om.piaspspd.grpc\x1a\x1bgoogle/protobuf/empty.proto\"\x19\n\tnameQuery\x12\x0c\n\x04name\x18\x01 \x01(\t\"6\n\x07Product\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x02\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x05\x32\xa6\x02\n\x0eProductService\x12\x46\n\nGetProduct\x12\x1c.com.piaspspd.grpc.nameQuery\x1a\x1a.com.piaspspd.grpc.Product\x12@\n\naddProduct\x12\x1a.com.piaspspd.grpc.Product\x1a\x16.google.protobuf.Empty\x12\x45\n\rremoveProduct\x12\x1c.com.piaspspd.grpc.nameQuery\x1a\x16.google.protobuf.Empty\x12\x43\n\rupdateProduct\x12\x1a.com.piaspspd.grpc.Product\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NAMEQUERY']._serialized_start=65
  _globals['_NAMEQUERY']._serialized_end=90
  _globals['_PRODUCT']._serialized_start=92
  _globals['_PRODUCT']._serialized_end=146
  _globals['_PRODUCTSERVICE']._serialized_start=149
  _globals['_PRODUCTSERVICE']._serialized_end=443
# @@protoc_insertion_point(module_scope)
