# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cadastro.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'cadastro.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63\x61\x64\x61stro.proto\x12\x08\x63\x61\x64\x61stro\"\x1f\n\x0f\x43\x61\x64\x61stroRequest\x12\x0c\n\x04nome\x18\x01 \x01(\t\"M\n\rCadastroReply\x12\x10\n\x08mensagem\x18\x01 \x01(\t\x12*\n\x07request\x18\x02 \x03(\x0b\x32\x19.cadastro.CadastroRequest2M\n\x08\x43\x61\x64\x61stro\x12\x41\n\tCadastrar\x12\x19.cadastro.CadastroRequest\x1a\x17.cadastro.CadastroReply(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cadastro_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CADASTROREQUEST']._serialized_start=28
  _globals['_CADASTROREQUEST']._serialized_end=59
  _globals['_CADASTROREPLY']._serialized_start=61
  _globals['_CADASTROREPLY']._serialized_end=138
  _globals['_CADASTRO']._serialized_start=140
  _globals['_CADASTRO']._serialized_end=217
# @@protoc_insertion_point(module_scope)
