# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logs.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'logs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nlogs.proto\x12\x04logs\"\x1a\n\nLogRequest\x12\x0c\n\x04nome\x18\x01 \x01(\t\"\x1b\n\x08LogReply\x12\x0f\n\x07message\x18\x01 \x01(\t26\n\x04Logs\x12.\n\x08showLogs\x12\x10.logs.LogRequest\x1a\x0e.logs.LogReply0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGREQUEST']._serialized_start=20
  _globals['_LOGREQUEST']._serialized_end=46
  _globals['_LOGREPLY']._serialized_start=48
  _globals['_LOGREPLY']._serialized_end=75
  _globals['_LOGS']._serialized_start=77
  _globals['_LOGS']._serialized_end=131
# @@protoc_insertion_point(module_scope)
